/*
  Warnings:

  - You are about to drop the column `postId` on the `Posts` table. All the data in the column will be lost.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Posts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "content" STRING NOT NULL,
    "userId" INT4 NOT NULL,

    CONSTRAINT "Posts_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Posts_userId_key";
INSERT INTO "_prisma_new_Posts" ("content","title","userId") SELECT "content","title","userId" FROM "Posts";
DROP TABLE "Posts" CASCADE;
ALTER TABLE "_prisma_new_Posts" RENAME TO "Posts";
CREATE UNIQUE INDEX "Posts_userId_key" ON "Posts"("userId");
ALTER TABLE "Posts" ADD CONSTRAINT "Posts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
